[theme]
base = "light"
primaryColor = "#5a7d8c"
backgroundColor = "#f2f2f4"
secondaryBackgroundColor = "#fcfcfd"
textColor = "#3a3a3c"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
